### ISSUE TITLE
Missing Dependencies in Git

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.app.apidoc#2]
These zopefoundation dependencies aren't in git. @jimfulton could you please add them from subversion when convenient? (I know that looks like a lot! No rush, there are still a handful of other projects that need updating.)

- zope.app.onlinehelp
- zope.app.preference
- zope.app.renderer
- zope.app.tree
- zope.app.file

**Comment by jimfulton** [comment]
On Fri, May 12, 2017 at 7:07 AM, Jason Madden <notifications@github.com>
wrote:

> These zopefoundation dependencies aren't in git. @jimfulton
> <https://github.com/jimfulton> could you please add them from subversion
> when convenient? (I know that looks like a lot! No rush, there are still a
> handful of other projects that need updating.)
>
>    - zope.app.onlinehelp
>    - zope.app.preference
>    - zope.app.renderer
>    - zope.app.tree
>    - zope.app.file
>
> No problem. I actually updated the process when I did zope.app.component
and it seems to be working a lot easier.

**Comment by jimfulton** [comment]
Done

**Comment by jamadden** [comment]
Thank you!

**Comment by jamadden** [comment]
The `zope.app.renderer` repository only contains a `MOVED_TO_GITHUB` file on the master branch. It has a 3.5 branch whose tip *seems* to match the published 3.5.1 that's on PyPI, at least as far as the version number goes. I will start with that branch, I guess.

**Comment by jimfulton** [comment]
Yeah, I noticed that. Of course, it make sense that 3.5.1 would have been released from that branch.  Clearly, someone thought it *had* been moved to git already.
