### ISSUE TITLE
Don't import __main__.py files

### ISSUE THREAD

**Issue by jkmartindale** [zopefoundation/zope.app.apidoc#22]
It looks like `static-apidoc` is importing `__main__.py` files, which not only adds noise to stdout but could potentially lead to some other problems. By convention `__main__.py` is not useful and somewhat dangerous to introspect, so apidoc should just ignore it.

Would the best way to go about doing this be to add `__main__.py` to `IGNORE_FILES` in `codemodule/module.py`?

**Comment by jamadden** [comment]
That seems reasonable to me. `IGNORE_FILES` ought to do the trick.
