### ISSUE TITLE
Replace callableURL with absoluteURL in static.py

### ISSUE THREAD

**Issue by jkmartindale** [zopefoundation/zope.app.apidoc#24]
As far as I know, the only difference between `callableURL` and `absoluteURL` is that the former retains GET variables and the like and is used for accessing pages. I don't quite understand the rationale for keeping these variables in the URL when accessing pages.

The only instance I know of where these variables are used are ifacemodule's links to ZCML files, where the `line` variable highlights a particular line of interest. This works well for live documentation but not for a static export, as the static file will highlight the first line used to access the page, even though the user may access the page from a link to a different line.

An example of this is `/++apidoc++/Code/zope/app/localpermission/browser.zcml/index.html`. Its line 16 is referenced by `/++apidoc++/Interface/zope.browser.interfaces.IAdding/index.html` while its line 24 is referenced by `/++apidoc++/Interface/zope.security.interfaces.IPermission/index.html`. Ideally, neither of these lines should be highlighted in the static export. This will happen if the GET variables are stripped, which will happen if `absoluteURL` is used instead of `callableURL`.

**Comment by jamadden** [comment]
There's also a difference when fragments are part of the query, e.g., `http://localhost/++apidoc++/Code/zope/app/apidoc/utilities.rst#id1` (the absoluteURL drops the fragment, the callable URL preserves it). But that's a difference that makes no difference, AFAICS.

I can confirm that using the absoluteURL results in the loss of highlighting, which is probably what we want. 

It also apparently results in a secondary change to a bunch of the files, for reasons that aren't clear: they lose their `<base>` tag:

```patch
diff -u -r /tmp/apidoc-nti-callable/++apidoc++/Code/zope/deprecation/deprecation/DeprecationProxy/index.html /tmp/apidoc-nti/++apidoc++/Code/zope/deprecation/deprecation/DeprecationProxy/index.html
--- /tmp/apidoc-nti-callable/++apidoc++/Code/zope/deprecation/deprecation/DeprecationProxy/index.html	2018-08-17 09:14:10.000000000 -0500
+++ /tmp/apidoc-nti/++apidoc++/Code/zope/deprecation/deprecation/DeprecationProxy/index.html	2018-08-17 09:27:34.000000000 -0500
@@ -3,8 +3,6 @@
 <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

   <head>
-<base href="../../../../../../++apidoc++/Code/zope/deprecation/deprecation/DeprecationProxy/index.html" />
-
     <title>Zope 3 apidoc</title>
```

But those base tags seem completely redundant.

There's enough non-determinisim in the output that it's somewhat hard to compare a diff (e.g., we should sort the methods and attributes of interfaces), but spot checking it looks right to me. So I'm +1 for this change.
